version: "1.0.0"

services:
  db:
    container_name: mydb
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: JobBoard
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    image: backend
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres?schema=public
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: {}
